spring:
  kafka:
    # Перечисляем всех наших брокеров
    bootstrap-servers: host.docker.internal:29092
    producer:
      # Настраиваем сериализацию сообщений
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topics:
    test-topic: topic1
